# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hammertime}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Avdi Grimm}]
  s.date = %q{2011-05-27}
  s.description = %q{When this library is required, it replaces the default Ruby exception-raising
behavior.  When an error is raised, the developer is presented with a menu
enabling them to ignore the error, view a stack trace, debug the error using IRB
or ruby-debug, and more.
}
  s.email = %q{avdi@avdi.org}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "example.rb",
    "hammertime.gemspec",
    "lib/hammertime.rb",
    "spec/hammertime_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/avdi/hammertime}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.2}
  s.summary = %q{Exception debugging console for Ruby}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-debug19>, ["~> 0.11"])
      s.add_runtime_dependency(%q<highline>, ["~> 1.6"])
      s.add_development_dependency(%q<rspec>, [">= 2.6.0"])
    else
      s.add_dependency(%q<ruby-debug19>, ["~> 0.11"])
      s.add_dependency(%q<highline>, ["~> 1.6"])
      s.add_dependency(%q<rspec>, [">= 2.6.0"])
    end
  else
    s.add_dependency(%q<ruby-debug19>, ["~> 0.11"])
    s.add_dependency(%q<highline>, ["~> 1.6"])
    s.add_dependency(%q<rspec>, [">= 2.6.0"])
  end
end

